name: demo ci pipeline

on: 
  push:               #event where gist listening for
    branches:         #pipeline only run if code is push in main branch.
      - main
    paths:
      - 'demo/**' #this ensure pipeline onlyrun if any changes inside demo folder (ADS) refrence

jobs:                #this is actual block of code
  validate-yaml:      #you can give any name( this is just a custome name given to jobs)
    runs-on: ubuntu-latest #the server provided by github, absoulately free and empty(also free insize)

    steps:
    - name:  1. Checkout Code  #
      uses: actions/checkout@v4 # this download the code from repo and place to new ubuntu VM

    - name: 2. Validate YAML Syntax
      run: |
        python3 -c 'import yaml, glob; [list(yaml.safe_load_all(open(f))) for f in glob.glob("demo/*.yaml") + glob.glob("demo/*.yml")]'